# Generated by Django 6.0.5 on 2026-05-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cargo', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMEIRO', 'Enfermeiro'), ('RECEPCIONISTA', 'Recepcionista'), ('ADMIN', 'Administrador')], max_length=20)),
                ('especialidade', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
