# Generated by Django 6.0.5 on 2026-05-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('RECEPCIONISTA', 'Recepcionista'), ('ADMIN', 'Administrador')], max_length=20),
        ),
    ]
